### ISSUE TITLE
max_parse_response_bytes_count ->u8

### ISSUE THREAD

**Issue by zqlpaopao** [bk-rs/fbthrift-transport#6]
The maximum number of responses that can be returned for the u8 type is 255. If a large amount of data is found during the query, an error will occur. Would it be better to set it to u32 or u64

**Comment by vkill** [comment]
Hi @zqlpaopao 
Generally you can increase `buf_size` and `max_buf_size`. 
Even if the result is large, if the network is normal, u8 is enough.

```
            buf_size: 1024,
            max_buf_size: 1024 * 4,
            read_timeout: Duration::from_secs(5),
            max_parse_response_bytes_count: 3,
```

**Comment by zqlpaopao** [comment]
> Hi @zqlpaopao Generally you can increase `buf_size` and `max_buf_size`. Even if the result is large, if the network is normal, u8 is enough.
> 
> ```
>             buf_size: 1024,
>             max_buf_size: 1024 * 4,
>             read_timeout: Duration::from_secs(5),
>             max_parse_response_bytes_count: 3,
> ```

Okay, thank you very much
